databases:
  - name: hAts_DB
    databaseName: hats_db
    user: hAts
    region: singapore

services:
  - type: web
    name: hAts
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hAts
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

